const productos = [
  {
    id: 1,
    title: "Naranja",
    description: "naranjas dulces",
    thumbnail: "Imagen naranja",
    code: "M1234",
    price: 1200,
    stock: 12,
  },
  {
    id: 2,
    title: "Manzana",
    description: "manzana dulce",
    thumbnail: "Imagen manzana",
    code: "M1223",
    price: 2100,
    stock: 12,
  },
  {
    id: 3,
    title: "Sandia",
    description: "Sandia de italia",
    thumbnail: "Imagen Sandia",
    code: "M1299",
    price: 3200,
    stock: 12,
  },
  {
    id: 4,
    title: "Pera",
    description: "peras de francia",
    thumbnail: "Imagen Pera",
    code: "M1200",
    price: 4300,
    stock: 12,
  },
  {
    id: 5,
    title: "Guinda",
    description: "Guindas rojas",
    thumbnail: "Imagen Guinda",
    code: "M1211",
    price: 8000,
    stock: 12,
  },
  {
    id: 6,
    title: "Banana",
    description: "Banana de ecuador",
    thumbnail: "Imagen banana",
    code: "M1208",
    price: 1800,
    stock: 12,
  },
  {
    id: 7,
    title: "Arandanos",
    description: "Arandanos congelados",
    thumbnail: "Imagen Arandanos",
    code: "M1214",
    price: 600,
    stock: 12,
  },
  {
    id: 8,
    title: "Frutillas",
    description: "frutillas grandes",
    thumbnail: "Imagen Frutilla",
    code: "M1255",
    price: 900,
    stock: 12,
  },
  {
    id: 9,
    title: "Tomate",
    description: "Tomate perita",
    thumbnail: "Imagen Tomate",
    code: "M1204",
    price: 990,
    stock: 12,
  },
  {
    id: 10,
    title: "Lechuga",
    description: "Lechuga criolla",
    thumbnail: "Imagen Lechuga",
    code: "M1271",
    price: 1300,
    stock: 12,
  },
];

export default productos;
